baseURL = "https://jasongwq.github.io/gblog/"
languageCode = 'zh-CN'
title = 'My New Hugo Site'
theme = "hyde"

hasCJKLanguage = true
enableEmoji = true

[params] # 指定发布的文件目录和博客描述
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # description abou this website
  description = "There is only one thing in the world worse than being talked about, and that is not being talked about."
